### PR TITLE
Remove reading of unused byte

### PR DESCRIPTION
**Pull request by akdh**
In my tests the first byte of each word is being stripped, remove this read should fix the issue.

### CODE REVIEW

**Comment by dhowden** [comment]
What are you using the generate your models?  I'm not seeing this issue with our models generated by the official [Google word2vec tool](https://code.google.com/archive/p/word2vec/), which all have a `\n` following the vector.

From the original word2vec.c (snippet beginning line 560):

```c
    // Save the word vectors
    fprintf(fo, "%lld %lld\n", vocab_size, layer1_size);
    for (a = 0; a < vocab_size; a++) {
      fprintf(fo, "%s ", vocab[a].word);
      if (binary) for (b = 0; b < layer1_size; b++) fwrite(&syn0[a * layer1_size + b], sizeof(real), 1, fo);
      else for (b = 0; b < layer1_size; b++) fprintf(fo, "%lf ", syn0[a * layer1_size + b]);
      fprintf(fo, "\n");
    }
```

**Comment by akdh** [comment]
@dhowden Hmm, OK, thanks for the feedback. I'm using gensim so this may be an issue with that tool.

**Comment by akdh** [comment]
Although it looks like gensim adds '\n's: https://github.com/piskvorky/gensim/blob/develop/gensim/models/word2vec.py#L1023

**Comment by akdh** [comment]
It looks like gensim may be the issue here: https://github.com/piskvorky/gensim/blob/develop/gensim/models/word2vec.py#L1032

**Comment by dhowden** [comment]
@akdh can you have a look at #3 and verify that it works for you.

**Pull request closed without merging**
